name: Test Easy Installer/Updater CLI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    UBUNTU_VERSION: 20.04

jobs:
    test:
        runs-on: ubuntu-${UBUNTU_VERSION}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup dependencies
              run: |
                apt update && \
                apt install curl -y && \
                curl -LJO https://github.com/sv222/easy-installer-updater-cli/releases/download/v0.1.0/easy-package-installer && \
                chmod +x easy-package-installer && \
                mv easy-package-installer /usr/local/bin

            - name: Test CLI
              run: |
                easy-package-installer nginx

        # Add additional test commands here to test the functionality of the CLI
            - name: Test with different Ubuntu version 18.04
              if: always()
              env:
              UBUNTU_VERSION: 18.04
              runs-on: ubuntu-${UBUNTU_VERSION}

            - name: Test with different Ubuntu version 16.04
              if: always()
              env:
              UBUNTU_VERSION: 16.04
              runs-on: ubuntu-${UBUNTU_VERSION}