name: Test Easy Installer/Updater CLI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup dependencies
              run: |
                apt update && \
                apt install curl -y && \
                curl -LJO https://github.com/sv222/easy-installer-updater-cli/releases/download/v0.1.0/easy-package-installer && \
                chmod +x easy-package-installer && \
                mv easy-package-installer /usr/local/bin

            - name: Test CLI
              run: |
                easy-package-installer nginx
